name: firebase_admin_interop
description: Firebase Admin SDK for Dart written as a wrapper around official Node.js SDK.
version: 2.1.0
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  node_interop: ^1.0.3
  meta: ^1.1.8
  quiver_hashcode: ^2.0.0

dev_dependencies:
  test: ^1.15.7
  build_runner: ^1.7.4
  build_node_compilers: ^0.3.1
  build_test: ^0.10.12+1
