name: firebase_admin_interop
description: Interop for Firebase Admin Node SDK
version: 0.1.0-beta.2
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  node_interop: '>=0.1.0-beta.4 <0.2.0'
  firestore_interop: '>=0.0.1 <0.1.0'
  meta: ^1.0.5
  built_value: ^4.2.1

dev_dependencies:
  build: ^0.10.0
  build_runner: ^0.4.0
  built_value_generator: ^4.2.1
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.26.0'
  test: ^0.12.24

transformers:
  - $dart2js
  - node_interop
